MACRO(IncludeProjectSettings)
    set( options  )
    set( oneValueArgs QT )
    set( multiValueArgs )

    cmake_parse_arguments( _INCLUDE_PROJECT_SETTINGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )

    if ( "${_INCLUDE_PROJECT_SETTINGS_QT}" STREQUAL "" )
        if( DEFINED T42_GLOBAL_USE_QT )
            SET( _INCLUDE_PROJECT_SETTINGS_QT ${T42_GLOBAL_USE_QT} )
        endif()
    endif()
    #MESSAGE( STATUS "=================" )

    #MESSAGE( STATUS "IncludeProjectSettings CMAKE_CURRENT_LIST_DIR=${CMAKE_CURRENT_LIST_DIR}" )
    #MESSAGE( STATUS "IncludeProjectSettings _INCLUDE_PROJECT_SETTINGS_QT=${_INCLUDE_PROJECT_SETTINGS_QT}" )

    SET( CURR_DIR ${CMAKE_CURRENT_LIST_DIR} )
    get_filename_component(STOP_DIR ${CMAKE_SOURCE_DIR} DIRECTORY)
    #MESSAGE( STATUS "CURR_DIR=${CURR_DIR}" )
    #MESSAGE( STATUS "STOP_DIR=${STOP_DIR}" )
    
    SET( PROJECT_FOUND 0 )
    while( NOT ${CURR_DIR} STREQUAL ${STOP_DIR} )
        if ( _INCLUDE_PROJECT_SETTINGS_QT )
            #MESSAGE( STATUS "Checking ${CURR_DIR} for QtProject.cmake" )
            SET( currProjectFile "QtProject.cmake" )
        else()
            #MESSAGE( STATUS "Checking ${CURR_DIR} for Project.cmake" )
            SET( currProjectFile "Project.cmake" )
        endif()

        #MESSAGE( STATUS "Checking for ${currProjectFile} in ${CURR_DIR}" )

        if ( EXISTS "${CURR_DIR}/${currProjectFile}" )
            #MESSAGE( STATUS "Found ${CURR_DIR}/${currProjectFile}" )
            include( ${CURR_DIR}/${currProjectFile} )
            SET( PROJECT_FOUND 1 )
            break()
        endif()
        
        get_filename_component(CURR_DIR ${CURR_DIR} DIRECTORY)
    endwhile()

    if ( NOT PROJECT_FOUND )
        if ( _INCLUDE_PROJECT_SETTINGS_QT )
            #MESSAGE( STATUS "Checking ${CURR_DIR} for QtProject.cmake" )
            SET( currProjectFile "${CMAKE_SOURCE_DIR}/T42-CMakeUtils/QtProject.cmake" )
        else()
            #MESSAGE( STATUS "Checking ${CURR_DIR} for Project.cmake" )
            SET( currProjectFile "${CMAKE_SOURCE_DIR}/T42-CMakeUtils/Project.cmake" )
        endif()
        
        if ( EXISTS "${currProjectFile}" )
            #MESSAGE( STATUS "Found ${currProjectFile}" )
            include( ${currProjectFile} )
            SET( PROJECT_FOUND 1 )
        endif()
    endif()
    
    if ( NOT PROJECT_FOUND )
        if ( _INCLUDE_PROJECT_SETTINGS_QT )
            MESSAGE( FATAL_ERROR "No QtProject.cmake file found" )
        else()
            MESSAGE( FATAL_ERROR "No Project.cmake file found" )
        endif()
    endif()

ENDMACRO()
