find_package(InstallFile REQUIRED)

FUNCTION(CreateVersion)

    set( options SUBDIR)
    set( oneValueArgs MAJOR MINOR PATCH GITVERSION DIFF AHEAD TEMPLATE APP_NAME VENDOR HOMEPAGE PRODUCT_HOMEPAGE EMAIL BUILD_DATE BUILD_TIME COPYRIGHT START_YEAR)
    set( multiValueArgs )
    cmake_parse_arguments(
        PARSE_ARGV 0
        _CREATE_VERSION
        "${options}"
        "${oneValueArgs}"
        "${multiValueArgs}"
        )

    set( DESC_FILE_NAME Version.h )
    set(OUTFILE "${CMAKE_BINARY_DIR}/Version.h")
    if ( _CREATE_VERSION_SUBDIR )
        set( DESC_FILE_NAME Version/Version.h )
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/Version")
        set(OUTFILE "${CMAKE_BINARY_DIR}/Version/Version.h")
    endif()
    
    set(TMP_OUTFILE ${OUTFILE}.tmp)
    
    if ( ( NOT _CREATE_VERSION_START_YEAR ) OR ( "${_CREATE_VERSION_START_YEAR}" STREQUAL "" ) )
        STRING(TIMESTAMP _CREATE_VERSION_START_YEAR "%Y")
    endif()
    
    STRING(TIMESTAMP CURR_YEAR "%Y")
    if ( ${_CREATE_VERSION_START_YEAR} STREQUAL ${CURR_YEAR} )
        SET( COPYRIGHT_YEARS "${_CREATE_VERSION_START_YEAR}"  )
    else()
        SET( COPYRIGHT_YEARS "${_CREATE_VERSION_START_YEAR}-${CURR_YEAR}" )
    endif()
    
    if ( ( NOT _CREATE_VERSION_COPYRIGHT ) OR ( "${_CREATE_VERSION_COPYRIGHT}" STREQUAL "" ) )
        STRING(TIMESTAMP _CREATE_VERSION_COPYRIGHT "Copyright © <COPYRIGHT_YEARS> Scott Aron Bloom and ${_CREATE_VERSION_VENDOR}")
    ENDIF()
    
    if ( ( NOT _CREATE_VERSION_TEMPLATE ) OR ( "${_CREATE_VERSION_TEMPLATE}" STREQUAL "" ) )
        SET( _CREATE_VERSION_TEMPLATE ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Version.h.in )
    endif()
    set( TEMPLATE_FILE ${_CREATE_VERSION_TEMPLATE} )
    
    if ( NOT EXISTS ${TEMPLATE_FILE} )
        MESSAGE( FATAL_ERROR "Could not find Version Template file '${TEMPLATE_FILE}'" )
    endif()
    
    if ( ( NOT _CREATE_VERSION_BUILD_DATE ) OR ( "${_CREATE_VERSION_BUILD_DATE}" STREQUAL "" ) )
        STRING(TIMESTAMP _CREATE_VERSION_BUILD_DATE "%m/%d/%Y" UTC)
    endif()
    
    if ( ( NOT _CREATE_VERSION_BUILD_TIME ) OR ( "${_CREATE_VERSION_BUILD_TIME}" STREQUAL "" ) )
        STRING(TIMESTAMP _CREATE_VERSION_BUILD_TIME "%H:%M:%SUTC" UTC)
    endif()

    STRING(REPLACE "<COPYRIGHT_YEARS>" ${COPYRIGHT_YEARS} _CREATE_VERSION_COPYRIGHT ${_CREATE_VERSION_COPYRIGHT})
    #MESSAGE( STATUS "===========================" )
    foreach( CURR IN LISTS oneValueArgs)
        #message( STATUS "_CREATE_VERSION_${CURR}=${_CREATE_VERSION_${CURR}}" )
        if ( "${_CREATE_VERSION_${CURR}}" STREQUAL "" ) # dont use NOT ${_CREATE_VERSION_${CURR} as Zero is avalid value
            MESSAGE( FATAL_ERROR "CreateVersion called without '${CURR}' parameter set" )
        endif()
    endforeach()
    #MESSAGE( STATUS "===========================" )

    message( CHECK_START "Generating/Updating ${DESC_FILE_NAME}" )

    set(VERSION_FILE_MAJOR_VERSION ${_CREATE_VERSION_MAJOR})
    set(VERSION_FILE_MINOR_VERSION ${_CREATE_VERSION_MINOR})
    set(VERSION_FILE_PATCH_VERSION ${_CREATE_VERSION_PATCH})
    set(VERSION_FILE_GIT_VERSION ${_CREATE_VERSION_GITVERSION})
    MATH( EXPR VERSION_FILE_PATCH_VERSION_LOW  "0x${_CREATE_VERSION_GITVERSION} & 0x0000FFFF" OUTPUT_FORMAT DECIMAL)
    MATH( EXPR VERSION_FILE_PATCH_VERSION_HIGH "(0x${_CREATE_VERSION_GITVERSION} & 0xFFFF0000)>>16" OUTPUT_FORMAT DECIMAL)
    STRING(TOLOWER ${_CREATE_VERSION_DIFF} VERSION_FILE_DIFF)
    set(VERSION_FILE_AHEAD         ${_CREATE_VERSION_AHEAD})
    set(VERSION_FILE_APP_NAME      ${_CREATE_VERSION_APP_NAME})
    set(VERSION_FILE_VENDOR        ${_CREATE_VERSION_VENDOR})
    set(VERSION_FILE_HOMEPAGE      ${_CREATE_VERSION_HOMEPAGE})
    set(VERSION_FILE_PRODUCT_HOMEPAGE ${_CREATE_VERSION_PRODUCT_HOMEPAGE})
    set(VERSION_FILE_EMAIL         ${_CREATE_VERSION_EMAIL})
    set(VERSION_FILE_BUILD_DATE    ${_CREATE_VERSION_BUILD_DATE})
    set(VERSION_FILE_BUILD_TIME    ${_CREATE_VERSION_BUILD_TIME})
    set(VERSION_FILE_COPYRIGHT     ${_CREATE_VERSION_COPYRIGHT})
    set(VERSION_FILE_START_YEAR    ${_CREATE_VERSION_START_YEAR})

    configure_file(
        "${TEMPLATE_FILE}"
        "${TMP_OUTFILE}"
    )

    set( VERSION_FILE_GIT_VERSION ${VERSION_FILE_GIT_VERSION} PARENT_SCOPE )
    set( VERSION_FILE_PATCH_VERSION_LOW ${VERSION_FILE_PATCH_VERSION_LOW} PARENT_SCOPE )
    set( VERSION_FILE_PATCH_VERSION_HIGH ${VERSION_FILE_PATCH_VERSION_HIGH} PARENT_SCOPE )
    InstallFile( ${TMP_OUTFILE} ${OUTFILE} REMOVE_ORIG ) # creates a dependency on TMP_OUTFILE

    set_property( 
        DIRECTORY ${CMAKE_SOURCE_DIR} 
        APPEND
        PROPERTY CMAKE_CONFIGURE_DEPENDS
        ${OUTFILE}
        )
    message(CHECK_PASS "Generated/Updated" )

ENDFUNCTION()
